### ISSUE TITLE
Doesn't work with Github windows runners

### ISSUE THREAD

**Issue by josipmaricevic** [mskelton/setup-yarn#2]
As the title says, action doesn't work with github hosted windows runners.

For example:
```yaml
name: Minimum example workflow
on:
  push:
    branch:
    - develop
 
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Yarn install
      uses: mskelton/setup-yarn@v1
      with:
        node-version: '10.x'
```

Will pass on Ubuntu and macOS, but fail on Windows with:
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib'
