### ISSUE TITLE
bug: `setup-yarn` unexpectedly invokes `actions/checkout` with `fetch-depth:1`

### ISSUE THREAD

**Issue by davidalpert** [mskelton/setup-yarn#3]
A colleague and I spent nearly three hours today trying to figure out why our build was failing reporting only a single commit was present after we had explicitly configured `actions/checkout` with `fetch-depth:0` in a previous step in our workflow.

It wasn't until we cracked open the detailed output of this `setup-yarn` action that we discovered it embeds what appears to be an unnecessary `actions/checkout` action with the `fetch-depth` hard-coded to `1`:

![image](https://user-images.githubusercontent.com/112503249/194179063-c9b9f887-49b3-4700-8b46-90e1b2f46ce8.png)

our workaround was to remove the `mskelton/setup-yarn` action and revert to `action/setup-node` and a simple run script to install yarn
```
     - name: install yarn
       run: npm install --global yarn
```

**Comment by mskelton** [comment]
Sorry for the confusion.  I feel like I should put a disclaimer in this repo that I really never intended this to be used by others, I use it for my projects as it's a really specific optimization to cleanup my workflows, but it's not really intended to be used outside of my projects.  If it works for you great, but it's not a typical open-source project in that I didn't build it for others, I just built it to fix a pain point for my projects.

I don't plan on adding support for changing the fetch depth.  Again, as I mentioned I don't really intend on supporting other people's use cases in this repo, it's really just a repo I use personally.  If you look at the source of this repo, you'll find it's pretty basic:

```yml
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
    - name: Install dependencies
      run: yarn install --immutable ${{ inputs.flags }}
      shell: bash
```

Also, I should mention as well that you don't need to run `npm install --global yarn`.  Yarn comes installed when you use the `setup-node` action, so you don't need to do that manually.
